version: 2

models:
  - name: monthly_spending
    columns:
      - name: month
        tests:
          - not_null
      - name: category_name
        tests:
          - not_null

  - name: category_trends
    columns:
      - name: month
        tests:
          - not_null
      - name: category_name
        tests:
          - not_null

  - name: monthly_cash_flow
    columns:
      - name: month
        tests:
          - not_null
      - name: category_type
        tests:
          - not_null

  - name: top_merchants
    columns:
      - name: merchant
        tests:
          - not_null

  - name: net_worth
    columns:
      - name: account_id
        tests:
          - unique
          - not_null
